SRC_CPPS = \
           displaythread.cpp \
           IGVTrueSenseUISampleDlg.cpp \
           TrueSenseConverter.cpp \
           main.cpp \

EXEC     = IGVTrueSenseUISampleDlg

include ../sample.Makefile
