# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingdlg.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_settingdlg(object):
    def setupUi(self, settingdlg):
        settingdlg.setObjectName("settingdlg")
        settingdlg.resize(670, 520)
        self.verticalLayout = QtWidgets.QVBoxLayout(settingdlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(settingdlg)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.camera_tab = QtWidgets.QWidget()
        self.camera_tab.setObjectName("camera_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.camera_tab)
        self.horizontalLayout_2.setContentsMargins(1, -1, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.camparamgbox = QtWidgets.QGroupBox(self.camera_tab)
        self.camparamgbox.setObjectName("camparamgbox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.camparamgbox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.camparamgbox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.cameranumlabel = QtWidgets.QLabel(self.camparamgbox)
        self.cameranumlabel.setObjectName("cameranumlabel")
        self.horizontalLayout_6.addWidget(self.cameranumlabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.camparamgbox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.cameranumsbox = QtWidgets.QSpinBox(self.camparamgbox)
        self.cameranumsbox.setMinimum(1)
        self.cameranumsbox.setMaximum(1)
        self.cameranumsbox.setObjectName("cameranumsbox")
        self.horizontalLayout_8.addWidget(self.cameranumsbox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.camparamgbox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.cameratypecbox = QtWidgets.QComboBox(self.camparamgbox)
        self.cameratypecbox.setObjectName("cameratypecbox")
        self.cameratypecbox.addItem("")
        self.horizontalLayout_5.addWidget(self.cameratypecbox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.camparamgbox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.cameraidcbox = QtWidgets.QComboBox(self.camparamgbox)
        self.cameraidcbox.setObjectName("cameraidcbox")
        self.horizontalLayout_7.addWidget(self.cameraidcbox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.opencamerabtn = QtWidgets.QPushButton(self.camparamgbox)
        self.opencamerabtn.setObjectName("opencamerabtn")
        self.verticalLayout_4.addWidget(self.opencamerabtn)
        self.balancebtn = QtWidgets.QPushButton(self.camparamgbox)
        self.balancebtn.setObjectName("balancebtn")
        self.verticalLayout_4.addWidget(self.balancebtn)
        spacerItem = QtWidgets.QSpacerItem(20, 308, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.vcameragbox = QtWidgets.QGroupBox(self.camparamgbox)
        self.vcameragbox.setCheckable(True)
        self.vcameragbox.setChecked(False)
        self.vcameragbox.setObjectName("vcameragbox")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.vcameragbox)
        self.horizontalLayout_9.setContentsMargins(1, 3, 1, 3)
        self.horizontalLayout_9.setSpacing(3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.vcameragbox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.camfileedit = QtWidgets.QLineEdit(self.vcameragbox)
        self.camfileedit.setObjectName("camfileedit")
        self.horizontalLayout_9.addWidget(self.camfileedit)
        self.openfilebtn = QtWidgets.QPushButton(self.vcameragbox)
        self.openfilebtn.setMinimumSize(QtCore.QSize(31, 27))
        self.openfilebtn.setMaximumSize(QtCore.QSize(31, 27))
        self.openfilebtn.setObjectName("openfilebtn")
        self.horizontalLayout_9.addWidget(self.openfilebtn)
        self.verticalLayout_4.addWidget(self.vcameragbox)
        self.horizontalLayout_2.addWidget(self.camparamgbox)
        self.previewgbox = QtWidgets.QGroupBox(self.camera_tab)
        self.previewgbox.setObjectName("previewgbox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.previewgbox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.previewlayout = QtWidgets.QVBoxLayout()
        self.previewlayout.setObjectName("previewlayout")
        self.verticalLayout_6.addLayout(self.previewlayout)
        self.horizontalLayout_2.addWidget(self.previewgbox)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.tabWidget.addTab(self.camera_tab, "")
        self.infrared_tab = QtWidgets.QWidget()
        self.infrared_tab.setObjectName("infrared_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.infrared_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.infrared_tab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.infraredcBox = QtWidgets.QComboBox(self.infrared_tab)
        self.infraredcBox.setObjectName("infraredcBox")
        self.horizontalLayout.addWidget(self.infraredcBox)
        self.opendevicebtn = QtWidgets.QPushButton(self.infrared_tab)
        self.opendevicebtn.setObjectName("opendevicebtn")
        self.horizontalLayout.addWidget(self.opendevicebtn)
        self.closeBtn = QtWidgets.QPushButton(self.infrared_tab)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout.addWidget(self.closeBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(4, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.messagegroupBox = QtWidgets.QGroupBox(self.infrared_tab)
        self.messagegroupBox.setObjectName("messagegroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.messagegroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.messageEdit = QtWidgets.QPlainTextEdit(self.messagegroupBox)
        self.messageEdit.setPlainText("")
        self.messageEdit.setObjectName("messageEdit")
        self.verticalLayout_2.addWidget(self.messageEdit)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sendEdit = QtWidgets.QLineEdit(self.messagegroupBox)
        self.sendEdit.setObjectName("sendEdit")
        self.horizontalLayout_4.addWidget(self.sendEdit)
        self.sendBtn = QtWidgets.QPushButton(self.messagegroupBox)
        self.sendBtn.setObjectName("sendBtn")
        self.horizontalLayout_4.addWidget(self.sendBtn)
        self.clearBtn = QtWidgets.QPushButton(self.messagegroupBox)
        self.clearBtn.setObjectName("clearBtn")
        self.horizontalLayout_4.addWidget(self.clearBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.messagegroupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.receivecbox = QtWidgets.QComboBox(self.messagegroupBox)
        self.receivecbox.setEnabled(True)
        self.receivecbox.setObjectName("receivecbox")
        self.horizontalLayout_3.addWidget(self.receivecbox)
        self.label_3 = QtWidgets.QLabel(self.messagegroupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.commandcbox = QtWidgets.QComboBox(self.messagegroupBox)
        self.commandcbox.setEditable(True)
        self.commandcbox.setObjectName("commandcbox")
        self.commandcbox.addItem("")
        self.commandcbox.addItem("")
        self.commandcbox.addItem("")
        self.commandcbox.addItem("")
        self.commandcbox.addItem("")
        self.commandcbox.addItem("")
        self.commandcbox.addItem("")
        self.commandcbox.addItem("")
        self.commandcbox.addItem("")
        self.commandcbox.addItem("")
        self.commandcbox.addItem("")
        self.horizontalLayout_3.addWidget(self.commandcbox)
        self.confirmBtn = QtWidgets.QPushButton(self.messagegroupBox)
        self.confirmBtn.setObjectName("confirmBtn")
        self.horizontalLayout_3.addWidget(self.confirmBtn)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.messagegroupBox)
        self.tabWidget.addTab(self.infrared_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(settingdlg)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(settingdlg)

    def retranslateUi(self, settingdlg):
        _translate = QtCore.QCoreApplication.translate
        settingdlg.setWindowTitle(_translate("settingdlg", "Setting"))
        self.camparamgbox.setTitle(_translate("settingdlg", "Camera param"))
        self.label_5.setText(_translate("settingdlg", "camera num"))
        self.cameranumlabel.setText(_translate("settingdlg", "0"))
        self.label_8.setText(_translate("settingdlg", "Set Camera"))
        self.label_4.setText(_translate("settingdlg", "camera type"))
        self.cameratypecbox.setItemText(0, _translate("settingdlg", "mindvision"))
        self.label_6.setText(_translate("settingdlg", "Camera id"))
        self.opencamerabtn.setText(_translate("settingdlg", "open"))
        self.balancebtn.setText(_translate("settingdlg", "white balance"))
        self.vcameragbox.setTitle(_translate("settingdlg", "Virtual Camera"))
        self.label_7.setText(_translate("settingdlg", "FileDir"))
        self.openfilebtn.setText(_translate("settingdlg", "..."))
        self.previewgbox.setTitle(_translate("settingdlg", "Preview"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.camera_tab), _translate("settingdlg", "Camera"))
        self.label.setText(_translate("settingdlg", "Device Select:"))
        self.opendevicebtn.setText(_translate("settingdlg", "open"))
        self.closeBtn.setText(_translate("settingdlg", "close"))
        self.messagegroupBox.setTitle(_translate("settingdlg", "Command"))
        self.sendBtn.setText(_translate("settingdlg", "Send"))
        self.clearBtn.setText(_translate("settingdlg", "Clear"))
        self.label_2.setText(_translate("settingdlg", "Receive:"))
        self.label_3.setText(_translate("settingdlg", "SetAS:"))
        self.commandcbox.setItemText(0, _translate("settingdlg", "MENU"))
        self.commandcbox.setItemText(1, _translate("settingdlg", "RESET"))
        self.commandcbox.setItemText(2, _translate("settingdlg", "UP"))
        self.commandcbox.setItemText(3, _translate("settingdlg", "DOWN"))
        self.commandcbox.setItemText(4, _translate("settingdlg", "LEFT"))
        self.commandcbox.setItemText(5, _translate("settingdlg", "RIGHT"))
        self.commandcbox.setItemText(6, _translate("settingdlg", "VERSION"))
        self.commandcbox.setItemText(7, _translate("settingdlg", "F1"))
        self.commandcbox.setItemText(8, _translate("settingdlg", "F2"))
        self.commandcbox.setItemText(9, _translate("settingdlg", "F3"))
        self.commandcbox.setItemText(10, _translate("settingdlg", "F4"))
        self.confirmBtn.setText(_translate("settingdlg", "Confirm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infrared_tab), _translate("settingdlg", "Infrared"))

