SRC_CPPS = \
           aboutbox.cpp \
           actioncommanddlg.cpp \
           BufferOptions.cpp \
           bufferoptionsdlg.cpp \
           ChangeSourceTask.cpp \
           ConnectTask.cpp \
           Device.cpp \
           DeviceGEV.cpp \
           DeviceU3V.cpp \
           DisconnectTask.cpp \
           displayoptionsdlg.cpp \
           DisplayThread.cpp \
           ebusplayer.cpp \
           ebusplayerhandlers.cpp \
           ebusplayerlayout.cpp \
           ebusplayermenufile.cpp \
           ebusplayermenuhelp.cpp \
           ebusplayermenutools.cpp \
           errorsdlg.cpp \
           eventmonitordlg.cpp \
           filetransferdlg.cpp \
           filteringdlg.cpp \
           histogramwidget.cpp \
           ImageFiltering.cpp \
           imagesavedlg.cpp \
           ImageSaving.cpp \
           LoadTask.cpp \
           LogBuffer.cpp \
           main.cpp \
           Mp4WriterLinux.cpp \
           Mutex.cpp \
           ParameterInfo.cpp \
           Player.cpp \
           progressdlg.cpp \
           SaveTask.cpp \
           Setup.cpp \
           setupdlg.cpp \
           splashscreen.cpp \
           Stream.cpp \
           StreamGEV.cpp \
           StreamU3V.cpp \
           Task.cpp \
           warningdlg.cpp \

EXEC     = eBUSPlayer

include ../sample.Makefile
